---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

resources:
- 01-sealed-rhsso-client-secret.yaml
- 02-oauth.yaml

namespace: openshift-config

secretGenerator:
- name: matrix-login-template
  options:
    disableNameSuffixHash: true
  files:
    - config/login/login.html
- name: matrix-providers-template
  options:
    disableNameSuffixHash: true
  files:
    - config/login/providers.html 