---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
  namespace: openshift-sriov-network-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configDaemonNodeSelector:
    node-role.kubernetes.io/worker-pao: ""
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 2