apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: 00-default-cluster-config
 namespace: openshift-gitops
spec:
  generators:
# the list generator impose having cluster and url keys...
# should be fixed by https://github.com/argoproj-labs/applicationset/issues/162
  - list:
      elements:
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 01-openshift-gitops
            path: apps/01-openshift-gitops/overlay/hetzner
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 02-sealed-secrets
            path: apps/02-sealed-secrets
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 03-letsencrypt-certs
            path: apps/03-letsencrypt-certs
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 04-local-storage-operator
            wave: '4'
            path: apps/04-local-storage-operator
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 05-openshift-container-storage
            path: apps/05-openshift-container-storage
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 06-rhsso
            path: apps/06-rhsso/overlay/hetzner
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 07-oauth
            path: apps/07-oauth/overlay/hetzner
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 08-openshift-elasticsearch
            path: apps/08-openshift-elasticsearch
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 09-openshift-logging
            path: apps/09-openshift-logging
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 10-ansible-automation-platform
            path: apps/10-ansible-automation-platform
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 11-quay-container-security
            path: apps/11-quay-container-security
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 12-acm
            path: apps/12-advanced-cluster-management
        - cluster: hetzner
          url: https://kubernetes.default.svc
          values:
            name: 13-acs
            path: apps/13-acs/overlay/hetzner
  template:
    metadata:
      name: '{{values.name}}'
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/hook: Sync
    spec:
      project: default
      source:
        repoURL: https://github.com/adetalhouet/ocp-gitops.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
