---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  gitops/cluster-name: hetzner

bases:
  - ../../apps/01-openshift-gitops/argo-app
  - ../../apps/02-sealed-secrets/argo-app
  - ../../apps/03-letsencrypt-certs/argo-app
  - ../../apps/04-local-storage-operator/argo-app
  - ../../apps/05-openshift-container-storage/argo-app
  - ../../apps/06-rhsso/argo-app
  - ../../apps/07-oauth/argo-app
  # - ../../apps/08-openshift-elasticsearch/argo-app
  # - ../../apps/09-openshift-logging/argo-app
  # - ../../apps/10-ansible-automation-platform/argo-app
  # - ../../apps/11-quay-container-security/argo-app
  # - ../../apps/12-advanced-cluster-management/argo-app
  # - ../../apps/13-advanced-cluster-management-policies/argo-app
  # - ../../apps/14-advanced-cluster-management-apps/argo-app
# - ../../apps/14-advanced-cluster-management-observability/argo-app
  # - ../../apps/16-acs/argo-app