kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - https://github.com/redhat-cop/gitops-catalog/sealed-secrets-operator/overlays/default

patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: sealed-secrets-controller
    namespace: sealed-secrets
  path: update-status.yaml