---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: network-obs-groups
  namespace: network-observability
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: network-obs-operator
  namespace: network-observability
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: netobserv-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  