apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  agent: ipfix
  clusterNetworkOperator:
    namespace: openshift-network-operator
  consolePlugin:
    logLevel: info
    port: 9001
    register: true
    portNaming:
      enable: true
      portNames:
        '3100': loki
    imagePullPolicy: IfNotPresent
    image: 'quay.io/netobserv/network-observability-console-plugin:v0.1.2'
    replicas: 1
  ebpf:
    logLevel: info
    cacheMaxFlows: 1000
    imagePullPolicy: IfNotPresent
    excludeInterfaces:
      - lo
    cacheActiveTimeout: 5s
    interfaces: []
    image: 'quay.io/netobserv/netobserv-ebpf-agent:v0.1.0'
    sampling: 0
  flowlogsPipeline:
    logLevel: info
    port: 2055
    prometheusPort: 9090
    imagePullPolicy: IfNotPresent
    enableKubeProbes: true
    image: 'quay.io/netobserv/flowlogs-pipeline:v0.1.1'
    replicas: 1
    healthPort: 8080
    kind: DaemonSet
  ipfix:
    cacheActiveTimeout: 60s
    cacheMaxFlows: 100
    sampling: 1
  loki:
    timeout: 10s
    maxRetries: 10
    maxBackoff: 300s
    staticLabels:
      app: netobserv-flowcollector
    url: 'http://loki:3100/'
    batchWait: 1s
    minBackoff: 1s
    batchSize: 102400
    timestampLabel: TimeFlowEnd
  namespace: network-observability
