kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-config

secretGenerator:
- name: matrix-login-template
  options:
    disableNameSuffixHash: true
  files:
    - login.html
- name: matrix-providers-template
  options:
    disableNameSuffixHash: true
  files:
    - providers.html