apiVersion: v1
data:
  tls.crt: YOUR_CERT
  tls.key: YOUR_KEY
kind: Secret
metadata:
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  name: sealed-secrets-key
  namespace: sealed-secrets
type: kubernetes.io/tls
