apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-install-tower
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |

              wget https://releases.ansible.com/ansible-tower/setup_openshift/ansible-tower-openshift-setup-latest.tar.gz
              tar -xvf ansible-tower-openshift-setup-latest.tar.gz -C /tmp/ansible --strip-components=1
              cd /tmp/ansible
              ./setup_openshift.sh

          imagePullPolicy: Always
          name: postsync-install-tower
          volumeMounts:
          - name: ansible-tower-inventory
            mountPath: "/tmp/ansible/inventory"
            subPath: inventory
            readOnly: true
          - name: logs
            mountPath: "/logs"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ansible-tower-inventory
        secret:
          secretName: ansible-tower-inventory
      - name: logs
        emptyDir: {}