apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: tower
  namespace: ansible-automation-platform
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: true
  ingress_type: Route
  image_pull_policy: IfNotPresent
  task_privileged: false
  projects_persistence: false
  replicas: 1
  admin_user: admin