ocp-gitops:
  config:
    repoURL: https://github.com/adetalhouet/ocp-gitops.git
    overlay: ca-central

  applications:
    01-openshift-gitops:
      enabled: true
    02-sealed-secrets:
      enabled: true
    03-letsencrypt-certs:
      enabled: true
    04-local-storage-operator:
      enabled: true
    05-openshift-container-storage:
      enabled: true
    06-rhsso:
      enabled: true
    07-oauth:
      enabled: true
    08-openshift-elasticsearch:
      enabled: false
    09-openshift-logging:
      enabled: false
    10-ansible-automation-platform:
      enabled: true
    11-quay-container-security:
      enabled: false
    12-advanced-cluster-management:
      enabled: true
    13-advanced-cluster-management-policies:
      enabled: false
    14-advanced-cluster-management-apps:
      enabled: false
    15-advanced-cluster-managment-observability:
      enabled: true
    16-acs:
      enabled: true
      overlays: false