{{- $c := 1 | int64 }}
{{- range $key,$val := .Values.applications }}
{{- if $val.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: {{ quote $c |}}
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: {{ $.Values.config.repoURL }}
    targetRevision: HEAD
{{ if $val.overlays }}
    path: apps/{{ $key }}/overlays/{{ $.Values.config.overlay }}
{{ else }}
    path: apps/{{ $key }}
{{ end }}
  syncPolicy:
    automated: 
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
{{ $c = add1 $c }}
{{- end }}