apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: toweraccess
  namespace: open-cluster-management
spec:
  encryptedData:
    host: AgBB6AnoxoWaS+cXegvRsdrgcue9+CNlERuyDSLVdwT5w/JnfNPjY8Bh/cCYjRCwIhRakHgUlsuK+kYPV6WIJc9dy71PRM1gsOAJ7gDQDOZLpmPyz392JBB8dYGuHQpjMj3U+SiV8HpkWWid1E6MEtukbCUYJfLK031gV1FkRGzrYxoQgpzwtwhTyYIQJYsoZZdwQ4/vEPr/BOZ6NlU2eVqNT2dtLgFdVxG0jWOvBqGCTlYSRxDbRkNjM2bb745O4I/dif4rpxh1HW6zUGW9wN2jEYLRl0pvz82xmDDEN0Nx8WunUdXyVfEUAVEubDcf/F48QIFtND/SVpigL6fiKBSe9MWlR7Mm5pAuUM+d0ykJ2WoTX6cQz+kQkFz5aJhaURicLjJuMNVKH9PhUjHaLe18ZL3GzPiuNQjDRg/B3frbTcGYEcdQV6XI15iS4uASDC/HxcbPb5kCLc5S1kGE/hW13p4hsejS8xCktilbh3ZcLHMZWH2RXevbWjxxI8rgpXH2wVEm2inclNEZEq/OvspgR9SwdbQjK3/g0oUK3Lueirv79/NiN9nqYdVGDdq159o6fc38kSSY1E/CHgpq+epaulLwH4wnHpnpYAEfdppoUzHka9LuNkYDO4sjJ2fq3NlsdQenG+lK/pZVXDmpxl12vGT3oua0+1hqgZC6ZCI/aL/NCyLUJymLGsIQ7f5izKUR+/MR0NvTYKdw20oyimdX45GlUVJP5BX37leCnPhnn6XAdwwMae7r2ODZkws9gyrmA5+xw5Z0isaQR/E+nvhlVBEc8Pn1M0XVCTX4v2o=
    token: AgBxZRoupEQ7WNaavkM0DUJcz3DvJBS7ipiMB2T0RN5woZT7p9iFY8XilpVkzbakByaZD8HM+oV3IC35RzUYSOhb40mSPCUmUWNIDefWgK95fqZN+nlNDfhTAip6cWEF1VAzWfBEY6mhTtjzcgmRDWFR1lg3P0fYMUpL6BDj2pi3odxycns7UZvqOWNU80QO387X9l5o6W5Yz/WgYIuC39j0EZk4LmTWkysLS9oMMLixX13FFE3y4knytHx/pny1M8FTekpDGzVt7qsVPFUcqSanGv0i8wMwrKWiJy3z8szFoQPOxLvyVIVCOofJHzwOsD++ieZwtAEwM2Ivh3vNLFE4i0oI7mXjX5AcYNwOoL88eqk2yhwRpyckd6zkCoWyGlBYk4lPw7n30/ol0kSPiiQK3xTDlVL3+2gv4Io3/Gr4q8uZEkNrbm5yv4kVTsxiNX1vahY10+0CehOfQi1zktMDjwhD1Ds7YS5ij0kbzh2jAwBsJtC33yc9IQRpkciM80ycR5+E1Iyn53px23BAnjJilnHLIyKj496G/ISS9w/0iJnGuXGF6GaLJfHos+rOitMjWTVlxfHepCMY5o32fX5MkBkuk4DNIFt9SnLHzv1gZgbxVpowag05Ll+54o9D4z64/I05gknOjkGn2zHZ6aZ/hQh+u9EdK4eOTqbHFmIsU6AEGmQWUMTi1o2RQpNtI3RiFe3WH06XOXA+8epFbTF9bgKqkVvjYWVm8iixSHE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/type: ans
      name: toweraccess
      namespace: open-cluster-management
    type: Opaque

