apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ClusterCurator
metadata:
  name: cluster-automation
  namespace: acm-credentials
spec:
  destroy:
    posthook:
      - extra_vars:
          message: RHACM_CLUSTER_DELETION_ENDED
        name: send-slack-message-cluster-deploy
    prehook:
      - extra_vars:
          message: RHACM_CLUSTER_DELETION_STATED
        name: send-slack-message-cluster-deploy
    towerAuthSecret: tower
  install:
    posthook:
      - extra_vars:
          message: RHACM_CLUSTER_DEPLOYMENT_ENDED
        name: send-slack-message-cluster-deploy
    prehook:
      - extra_vars:
          message: RHACM_CLUSTER_DEPLOYMENT_STATED
        name: send-slack-message-cluster-deploy
    towerAuthSecret: tower
  scale:
    posthook:
      - extra_vars:
          message: RHACM_CLUSTER_SCALE_ENDED
        name: send-slack-message-cluster-deploy
    prehook:
      - extra_vars:
          message: RHACM_CLUSTER_SCALE_STATED
        name: send-slack-message-cluster-deploy
    towerAuthSecret: tower
  upgrade:
    posthook:
      - extra_vars:
          message: RHACM_CLUSTER_UPGRADE_ENDED
        name: send-slack-message-cluster-deploy
    prehook:
      - extra_vars:
          message: RHACM_CLUSTER_UPGRADE_STATED
        name: send-slack-message-cluster-deploy
    towerAuthSecret: tower
