apiVersion: v1
kind: Namespace
metadata:
  name: idp-mgmt-config
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocp410
  namespace: idp-mgmt-config
spec:
  displayName: ''
  image: 'registry.redhat.io/redhat/redhat-operator-index:v4.10'
  publisher: ''
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: idp-mgmt-operatorgroup
  namespace: idp-mgmt-config
spec:
  targetNamespaces:
  - idp-mgmt-config
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: idp-mgmt-operator-subscription
  namespace: idp-mgmt-config
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: alpha
  installPlanApproval: Automatic
  name: idp-mgmt-operator
---
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: IDPConfig
metadata:
  name: idp-config
  namespace: idp-mgmt-config
spec:
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: openidcacrt
  namespace: idp-mgmt-config
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFYzCCBEugAwIBAgISA2dFvGv30kQtQmEm396x7lrRMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMjA5MjIxMzQ2NDhaFw0yMjEyMjExMzQ2NDdaMCgxJjAkBgNVBAMT
    HWFwaS5jYS1jZW50cmFsLmFkZXRhbGhvdWV0LmNhMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAz3tasyRD5lw19RLTca2D+CHcj+8Og00GDFwZTa4ht4L0
    tIoc4xLjWXf+Um7C/sSzVTnqEYZPoa13kgR5ZET5mxfYeAHuXA+vGVUc23i1ZUsC
    ZjqAy5SxXG9fKolsNOTYMwxfXe7LIYzAad38pdcV5CDcNOKs+4Y0saKFTB7Tod1m
    TC5RanCEl/qmsrXUs9S4/qZkXkrhdDkrclYvaQ19KhyK9WwLs8FcmZRfTu6YSMwx
    F8shRa8TkkjfyV1niN69+PBgmZDVh+HzvSceWERuX5/Fq+36t52k89Zpi+7v2iPn
    mI5XvfXbK7o4KGr8V1jeivtZ3R8K6p/6yrrjM+zeKwIDAQABo4ICezCCAncwDgYD
    VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
    HRMBAf8EAjAAMB0GA1UdDgQWBBQpGicUD8g0v0Sii55VbJQOvgIzDTAfBgNVHSME
    GDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYB
    BQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDov
    L3IzLmkubGVuY3Iub3JnLzBKBgNVHREEQzBBgiAqLmFwcHMuY2EtY2VudHJhbC5h
    ZGV0YWxob3VldC5jYYIdYXBpLmNhLWNlbnRyYWwuYWRldGFsaG91ZXQuY2EwTAYD
    VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
    aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHz
    APEAdwBByMqx3yJGShDGoToJQodeTjGLGwPr60vHaPCQYpYG9gAAAYNlqmP+AAAE
    AwBIMEYCIQCFszbFKIvCYM0WGsp3Qk22pASSo3N11HWfm6RNocyvEAIhAK4MXlJS
    J6iUPBrujmXG0cIh8zuLGjFggGQLtViY8fV+AHYARqVV63X6kSAwtaKJafTzfREs
    QXS+/Um4havy/HD+bUcAAAGDZapj2gAABAMARzBFAiA5rEjEnEQpJcYrUYXQDNti
    CxnDMSBXPXW03AedNU3MggIhAN36LaLtF6DYiT8+i++uct/aIP6QDeXvwyC0eGPc
    98+JMA0GCSqGSIb3DQEBCwUAA4IBAQBgqWfHm4rJHRucKQ0QhdGBxXoazDjSdMk5
    2czO5lbAaKVyxPMcipeBAF5UBJ3YDc++ZL7O6ogaks7HNL6p8RsYc0lhqmXlF0EF
    9oOwOL4yGvfoE5aGCICyFCHDnU8395iOW5ilA80Nh/bJFjRqmKHO9raZHoU3v87B
    0yFo30yIagfgMvg0+mTzp3ouIIRRVQt/g/BAuzE549pW1xI8dwqsldNPYsrYBhu0
    Pil3of0tr2/YVIIq2jLeXlQtiksFio0fUSlqYr6pUIYV93RKQI2043zGqseJoLDB
    UdwMUcziJ9NbbRfcjsxv1BOUF3rkT/ow+MhJUzSD98xmtVwYp9qY
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----

    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
    ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
    wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
    LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
    4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
    bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
    sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
    Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
    FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
    SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
    PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
    TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
    c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
    +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
    ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
    b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
    U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
    MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
    5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
    9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
    WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
    he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
    Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
    -----END CERTIFICATE-----
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: identity-placement
  namespace: idp-mgmt-config
spec: {}
---
apiVersion: identityconfig.identitatem.io/v1alpha1
kind: AuthRealm
metadata:
  name: authrealm-openid
  namespace: idp-mgmt-config
spec:
  placementRef:
    name: identity-placement
  routeSubDomain: ad
  type: dex
  identityProviders:
    - name: oidc
      mappingMethod: add
      type: OpenID
      openID:
        ca:
          name: openidcacrt
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
            - username
        clientID: openshift
        clientSecret:
          name: keycloack-openshit-client-secret
        extraScopes: []
        issuer: >-
          https://keycloak-openshift-sso.apps.ca-central.adetalhouet.ca/auth/realms/openshift