---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/operator/overlays/release-2.3?ref=main
  - github.com/redhat-cop/gitops-catalog/advanced-cluster-management/instance/base?ref=main

resources:
- 01-sealed-tower-secret.yaml
- 02-cluster-curator.yaml