---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false

bases:
  - ../../base

patches:
-  target:
     kind: OAuth
     name: cluster
   patch: |-
    - op: replace
      path: /spec/identityProviders/0/openID/issuer
      value: >-
        https://keycloak-openshift-sso.apps.hub-adetalhouet.rhtelco.io/auth/realms/openshift