---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 12-advanced-cluster-management-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '14'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/adetalhouet/acm-playground.git
    targetRevision: HEAD
    path: apps/12-advanced-cluster-management-apps
  syncPolicy:
    automated: 
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m