apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '6'
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/06-oauth
    repoURL: https://github.com/adetalhouet/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true