---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-admin-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
  - kind: ServiceAccount
    name: openshift-gitops-argocd-server
    namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cli-job-sa-role
rules:
  # this is for the 00-presync-label-worker-job job
  - apiGroups:
    - "*"
    resources: ["nodes"]
    verbs:
    - list
    - get
    - patch
  # this is for the 00-presync-create-cert-cm-job
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: openshift-gitops
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-cluster-admin
roleRef: # hack for job ansible to run... FIXME
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: openshift-gitops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: openshift-gitops