apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-update-oidc-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          env:
          - name: OIDC_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-secret-oidc
                key: oidc.keycloak.clientSecret
          command:
            - /bin/bash
            - -c
            - |
              oc get secret -n openshift-gitops argocd-secret
              if [[ $? == 0 ]]
              then 
                export CLIENT_SECRET=$(echo ${OIDC_SECRET} | base64)
                oc patch secret argocd-secret -n openshift-gitops --type='json' -p='[{"op" : "add" ,"path" : "/data/oidc.keycloak.clientSecret" ,"value" : ''${CLIENT_SECRET}''}]'
              else
                echo "argocd-secret was not found in namesapce openshift-gitops"
                exit 1
              fi
          imagePullPolicy: Always
          name: postsync-update-oidc-secret
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: argocd-secret-oidc
        secret:
          secretName: argocd-secret-oidc