---
apiVersion: v1
kind: Secret
metadata: 
  namespace: openshift-gitops
  name: argocd-secret
data:
  oidc.keycloak.clientSecret: Y2xpZW50LXNlY3JldAo=
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  oidcConfig: |
    name: Keycloak
    issuer: https://keycloak-openshift-sso.apps.mgnt.adetalhouet.rhtelco.io/auth/realms/OpenShift
    clientID: argocd 
    clientSecret: $oidc.keycloak.clientSecret 
    requestedScopes: ["openid", "profile", "email", "groups"] 
  server:
    route:
      enabled: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-gitops
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, ArgoCDAdmins, role:admin