apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: lab-spoke-adetalhouet
  namespace: sno-ztp
  labels:
    cluster-name: lab-spoke-adetalhouet
spec:
  config:
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        ipv4:
          address:
            - ip: 148.251.12.37
              prefix-length: 32
          dhcp: false
          enabled: true
        ipv6:
          enabled: false
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 148.251.12.33
          next-hop-interface: eth0
  interfaces:
    - name: "eth0"
      macAddress: "00:50:56:01:15:94"