apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/00-sealed-secrets
    repoURL: https://github.com/adetalhouet/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true