apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: 00-default-cluster-config
 namespace: openshift-gitops
spec:
  generators:
# the list generator impose having cluster and url keys...
# should be fixed by https://github.com/argoproj-labs/applicationset/issues/162
  - list:
      elements:
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 01-openshift-gitops
            wave: '1'
            path: apps/01-openshift-gitops/overlay/default
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 02-sealed-secrets
            wave: '2'
            path: apps/02-sealed-secrets
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 03-letsencrypt-certs
            wave: '3'
            path: apps/03-letsencrypt-certs
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 04-local-storage-operator
            wave: '4'
            path: apps/04-local-storage-operator
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 05-openshift-container-storage
            wave: '5'
            path: apps/05-openshift-container-storage
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 06-rhsso
            wave: '6'
            path: apps/06-rhsso/overlay/default
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 07-oauth
            wave: '7'
            path: apps/07-oauth/overlay/default
        # - cluster: default
        #   url: https://kubernetes.default.svc
        #   values:
        #     name: 08-openshift-elasticsearch
        #     wave: '8'
        #     path: apps/08-openshift-elasticsearch
        # - cluster: default
        #   url: https://kubernetes.default.svc
        #   values:
        #     name: 09-openshift-logging
        #     wave: '9'
        #     path: apps/09-openshift-logging
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 10-ansible-automation-platform
            wave: '10'
            path: apps/10-ansible-automation-platform
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 11-quay-container-security
            wave: '11'
            path: apps/11-quay-container-security
        - cluster: default
          url: https://kubernetes.default.svc
          values:
            name: 13-acs
            wave: '13'
            path: apps/13-acs/overlay/default
  template:
    metadata:
      name: '{{values.name}}'
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{values.wave}}'
        argocd.argoproj.io/hook: Sync
    spec:
      project: default
      source:
        repoURL: https://github.com/adetalhouet/ocp-gitops.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true