---
apiVersion: v1
kind: Namespace
metadata:
  name: network-observability
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
  namespace: network-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---    
apiVersion: v1
kind: Pod
metadata:
  name: loki
  namespace: network-observability
  labels:
    app: loki
spec:
  volumes:
    - name: loki-store
      persistentVolumeClaim:
        claimName: loki-store
  containers:
    - name: loki
      image: grafana/loki
      volumeMounts:
        - mountPath: "/loki"
          name: loki-store
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: network-observability
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100