apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloack-openshit-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBz0VD0rZbpd6ZJM1jWJo+w0YdogsQNUsz9lRTre+Z9tuv5hxwowjHf5sYiyWO0Hv40OV/o/7cbUpoVtnW+Huhm9XRbk4f/JH87hK8cns+aE/Qf5nhGXl6Q2mATJejm0DDfvK0hCahH6vbvDQkIBRnYxnJDNr6WXe3YR5D2IV5sj223iWZ1LMhI+OM7LcCSaCD8QVvFaTC5cbptZ8K5Mo/efKGZg1g0pib9X3O/vMvon0eu28qDHynXgwvCLmQ+TyF0msNfmFP3TKXNknQEcTOx9F7Ph5fjtXkjZJIDSa+gfnNZLvVp9g0RAVfiorhVgecqC7e8ZM3zUcdO8SIh8DvYvxGTpsS/U5BBJqJZCSXlxnVsYZy5KTps5HteFTLtvWlEMvlbGeLwkdB5w+skF90G53MSc8axsGWLct2C9fV40BzNp0Q0pNNIGf7QU4g2fROXkqq85AYMFIciahrOsQkZkiyqzVXFz0TJwAHDgNpLUS3iJjKynINpSp7JU0EgOvavvzD5xlo9gHKIH55FVdSfbE9hoCP9uHJMNt0Wm11m00t4MvqtTQlQ9UocyHU590G90Okw/jDLugD04IjNij2+IVNsG/921W5yQsnGsHAiXYR1U34iHVS7dL2M7dwnNqzU8aCw1brdkRi06iinmNRUAbvockwWSeUXN6KqSbnxnMiNiv4hfWAuobSYJBayK2alCm5v5cqNHEOd7w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloack-openshit-client-secret
      namespace: openshift-config
    type: Opaque

