apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders: []
  templates:
    login:
      name: matrix-login-template
    providerSelection:
      name: matrix-providers-template