---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-useast2-cluster
spec:
  destination:
    namespace: ''
    server: 'https://api.apps-useast2-adetalhouet.rhtelco.io:6443'
  source:
    path: clusters/apps-useast2
    repoURL: 'https://github.com/adetalhouet/ocp-gitops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true 
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true