---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-namespace.yaml
- 01-acm-observability-bucket.yaml
- 02-install-observability.yaml
- 03-multiclusterobservability.yaml