global:
  resolve_timeout: 5m
  slack_api_url: >-
    https://hooks.slack.com/services/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
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_match:
      severity: critical
    target_match_re:
      severity: warning|info
  - equal:
      - namespace
      - alertname
    source_match:
      severity: warning
    target_match_re:
      severity: info
receivers:
  - name: Critical
    slack_configs:
      - channel: adetalhouet-sandbox
  - name: Default
    slack_configs:
      - channel: adetalhouet-sandbox
  - name: Watchdog
    slack_configs:
      - channel: adetalhouet-sandbox
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - receiver: Watchdog
      match:
        alertname: Watchdog
    - receiver: Critical
      match:
        severity: critical
