---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-cli-acs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: stackrox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: stackrox
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  name: prep-for-deployables
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              oc patch secret admission-control-tls -p '{"metadata": {"annotations":{"apps.open-cluster-management.io/deployables":"true"}}}'
              oc patch secret collector-tls -p '{"metadata": {"annotations":{"apps.open-cluster-management.io/deployables":"true"}}}'
              oc patch secret sensor-tls -p '{"metadata": {"annotations":{"apps.open-cluster-management.io/deployables":"true"}}}'

              ACS_HOST="$(oc get route -n stackrox central -o custom-columns=HOST:.spec.host --no-headers):443"
              ACS_HOST=$(echo ${ACS_HOST} | base64)
              oc patch secret sensor-tls  --type='json' -p='[{"op" : "add" ,"path" : "/data/acs-host" ,"value" : "'${ACS_HOST}'"}]'

          imagePullPolicy: IfNotPresent
          name: prep-for-deployables
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30