kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Namespace for the Let's Encrypt job.
namespace: letsencrypt-job

# Job resources.
resources:
  - 01-namespace.yaml
  - 02-job-serviceaccount.yaml
  - 03-rbac.yaml
  - 04-job.yaml
  - 05sealed-aws-credentials.yaml