---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: hub-cluster
spec:
  destination:
    namespace: ''
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: clusters/hub
    targetRevision: HEAD
    repoURL: 'https://github.com/adetalhouet/ocp-gitops.git'