kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

patches:
-  target:
     kind: Subscription
     name: ansible-automation-platform
   patch: |-
    - op: replace
      path: /metadata/namespace
      value: 'ansible-automation-platform'
    - op: add
      path: /spec/startingCSV
      value: ansible-automation-platform-operator.v2.0.0
    - op: add
      path: /spec/installPlanApproval
      value: Manual
-  target:
     kind: ConsoleLink
     name: tower
   patch: |-
    - op: replace
      path: /spec/href
      value: 'https://tower-ansible-automation-platform.apps.hetzner.sandbox1091.opentlc.com'