kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/operator/overlays/early-access?ref=main
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/instance/overlays/default?ref=main

patches:
-  target:
     kind: ConsoleLink
     name: tower
   patch: |-
    - op: replace
      path: /spec/href
      value: 'https://tower-ansible-automation-platform.apps.hub-adetalhouet.rhtelco.io'