apiVersion: batch/v1
kind: Job
metadata:
  name: presync-create-cert-cm-job
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              oc get configmap openidcacrt -n openshift-config
              if [[ $? == 1 ]]
              then 
                echo "Create a ConfigMap named openidcrt in the openshift-config project."
                
                # Get name of certs secret.  It can be router-certs or router-certs-default.
                CERT_SECRET=""
                while [[ z$CERT_SECRET == z ]]; do
                  echo "Wait for letencrypt certs to be deployed, sleep 3 seconds"
                  sleep 3
                  CERT_SECRET=$(oc get secrets -n openshift-ingress | grep 'le-certs' | cut -d ' ' -f1)
                done;
                echo "Certificate found - store in $CERT_SECRET"
                tlscert=`oc get secrets/$CERT_SECRET -o jsonpath={.data.'tls\.crt'} -n openshift-ingress | base64 --decode`
                oc create configmap openidcacrt --from-literal ca.crt="$tlscert" -n openshift-config
              fi
          imagePullPolicy: Always
          name: presync-create-cert-cm-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30