---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sso
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-sso
  namespace: openshift-sso
spec:
  targetNamespaces:
  - openshift-sso
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-sso
  namespace: openshift-sso
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
