---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: openshift-sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
  instances: 1
  storageClassName: ocs-storagecluster-ceph-rbd