kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/operator/overlays/stable-2.4-cluster-scoped?ref=main
  - github.com/redhat-cop/gitops-catalog/ansible-automation-platform/instance/overlays/default?ref=main

patches:
# -  target:
#      kind: OperatorGroup
#      name: ansible-automation-platform-operator
#    patch: |-
#     - op: replace
#       path: /spec/targetNamespaces
#       value: []
-  target:
     kind: ConsoleLink
     name: controller
   patch: |-
    - op: replace
      path: /spec/href
      value: 'https://controller-ansible-automation-platform.apps.ca-central.adetalhouet.ca'
-  target:
     kind: AutomationController
     name: controller
   patch: |-
    - op: add
      path: /spec/postgres_storage_class
      value: 'ocs-storagecluster-cephfs'
