---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - path: 07-patch-oidc-config.yaml
    target:
      group: argoproj.io
      kind: ArgoCD
      name: openshift-gitops
      version: v1alpha1