apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sso-secret
  namespace: stackrox
spec:
  encryptedData:
    clientSecret: AgCbfOBJ9itbHYGy54AK67MfVitHFHNAyPUtuhsRbhxqhd4sttRxzO5VWGdKfRTbwVXGoMjOKPQCew+K/KEGjTAu/gMl2MTiR9gYWHI2FXntJX8osQkNVvBJvPKsVGdjSIOIxwLZSv+wDRjmQARiXrWXHpTtRWhvFvugORo2BX0xHUDO9EKecs5gA/V5F1anWeMJq07n44LPE7E3ruc7rY9ok0SpM9quc3703BvMCHS9ouKz/1yAUjt2m5pKQbyZOraRi88/Cf8jGcZBvKNFms4ZBbU3AZ3XozgwBdhBS2eeT6y9kKnJejyoNWTnbZbQX/tXdyDgqzhVzGWhqH36fxLrYizbqJNKdzGKVHKZRHkDYOiMuf+dG4/rIOmizKAScw5Nn7GHps07hzGCI4tWSLDEiB+4Cj4fSF20cGG+hnvFoUt4XoX6ja2Cu9YZI7prNHdjx4qul5ayHnLBAiYyrWTwMGzBbfgtpk43LynHkN/7Hb1EH1Xc3qbAn/CHK/nOtKiAKdGhNyusCbOgx+Hgp6FrsL+9uand9VgrGvCGN65li/ZkqmcXvaTme3Pvkb0VVxOuj4JZ2t+zLeyvRcQJYEvHwvblY1QPI00SKGXXUhdqZVJkJTZUJyWbCLaWJf4BFjS2b+r2pzyQuS6GJSyI2ISEuEHxrwLfd/tiAOvkVYZwljc4Iu+lE9rMwsOTUAusBTXDIY4TEVu18ToLL60teghffGSYxiLt6CSJmXq2BsHnXvI1AjY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sso-secret
      namespace: stackrox
    type: Opaque

