kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - https://github.com/redhat-cop/gitops-catalog/acs-operator/overlays/aggregate-minimal

resources:
  - 01-console-link.yaml
  - 02-sealed-rhsso-client-secret.yaml
  - 03-job-sso-integration.yaml