apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: cluster-config
 namespace: openshift-gitops
spec:
  generators:
# the list generator impose having cluster and url keys...
# should be fixed by https://github.com/argoproj-labs/applicationset/issues/162
  - list:
      elements:
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: sealed-secrets
            path: apps/01-sealed-secrets
            wave: '1'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: letsencrypt-certs
            path: apps/02-letsencrypt-certs
            wave: '2'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: argocd
            path: apps/03-openshift-gitops
            wave: '3'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: local-storage-operator
            path: apps/04-local-storage-operator
            wave: '4'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: openshift-container-storage
            path: apps/05-openshift-container-storage
            wave: '5'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: 06-rhsso
            path: apps/06-rhsso
            wave: '6'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: config-console-links
            path: apps/07-oauth
            wave: '7'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: openshift-elasticsearch
            path: apps/05-openshift-container-storage
            wave: '8'
        - cluster: app-us-east-2
          url: https://kubernetes.default.svc
          values:
            name: openshift-logging
            path: apps/09-openshift-logging
            wave: '9'
  template:
    metadata:
      name: '{{values.name}}'
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{values.wave}}'
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      source:
        repoURL: https://github.com/adetalhouet/ocp-gitops.git
        targetRevision: main
        path: '{{values.path}}'
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true