---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
-  target:
     kind: ArgoCD
     name: openshift-gitops
   patch: |-
    - op: replace
      path: /spec/oidcConfig
      value: |
          name: Keycloak
          issuer: https://keycloak-openshift-sso.apps.test-adetalhouet.rhtelco.io/auth/realms/openshift
          clientID: argocd 
          clientSecret: $oidc.keycloak.clientSecret 
          requestedScopes: ["openid", "profile", "email", "groups"]