---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-presync-create-cert-cm-job.yaml
- 01-install.yaml
- 02-sealed-rhsso-config.yaml
- 03-sealed-rhsso-client-secret.yaml
- 04-postsync-keycloak-migration.yaml
- 06-oauth.yaml
