---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-presync-create-cert-cm-job.yaml
- 01-install.yaml
- 02-keycloak.yaml
- 03-sealed-rhsso-config.yaml
- 04-sealed-rhsso-client-secret.yaml
- 05-postsync-keycloak-migration.yaml
# - 06-oauth.yaml
