---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
    argocd.argoproj.io/hook: PreSync
  name: storace-cli-job-sa-role
rules:
  - apiGroups:
    - "*"
    resources: ["nodes", "storageclass"]
    verbs:
    - list
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storace-cli-gitops-rolebinding
  annotations:
    argocd.argoproj.io/hook: PreSync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storace-cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: openshift-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/hook: PreSync