# make sure the nodes are first labeled with cluster.ocs.openshift.io/openshift-storage=''
# ex: for i in `oc get nodes -l node-role.kubernetes.io/worker -o name`; do oc label $i cluster.ocs.openshift.io/openshift-storage=''; done
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryption:
    enable: true
  storageDeviceSets:
    - name: ocs-deviceset-gp2
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 512Gi
          storageClassName: gp2
          volumeMode: Block
      count: 1
      replica: 3
    - count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lso-blockclass
          volumeMode: Block
      name: ocs-deviceset2-lso-blockclass
      replica: 2
