apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  storageDeviceSets:
    - count: 3
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: localvolume-block
          volumeMode: Block
      name: ocs-deviceset-localvolume-block
      replica: 1
  encryption:
    kms: {}
  monDataDirHostPath: /var/lib/rook