apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  storageDeviceSets:
    - count: 5
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lso-blockclass
          volumeMode: Block
      name: ocs-deviceset-lso-blockclass
      replica: 1
    - count: 5
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lso-blockclass
          volumeMode: Block
      name: ocs-deviceset2-lso-blockclass
      replica: 1
  encryption:
    kms: {}
  monDataDirHostPath: /var/lib/rook
