---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocs-registry
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: ocs-storagecluster-cephfs
