---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-container-storage-operator/operator/overlays/stable-4.8?ref=main

resources:
- 00-cli-job-sa-and-role.yaml
- 01-presync-csi-tolerations.yaml
- 01-presync-label-worker-job.yaml
- 02-ocs-lso-storagecluster.yaml
- 07-postsync-default-storageclass.yaml