---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-data-foundation-operator/operator/overlays/stable-4.9?ref=main

resources:
- 00-cli-job-sa-and-role.yaml
- 01-presync-csi-tolerations.yaml
- 01-presync-label-worker-job.yaml
- 02-ocs-lso-storagecluster.yaml
- 04-registry-pvc-create.yaml
- 05-ocs-internal-registry.yaml
- 06-metrics-use-ocs.yaml
- 07-postsync-default-storageclass.yaml
