---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  namespace: openshift-sso
  name: adetalhouet
  labels:
    app: sso
spec:
  realmSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - sso
    matchLabels:
      app: sso
  user:
    lastName: de Talhouët
    enabled: true
    username: adetalhouet
    firstName: Alexis
    credentials:
      - type: password
        value: password
        temporary: true
