---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-install.yaml
- 02-keycloak.yaml
- 03-keycloak-realm.yaml
- 04-keycloak-client-openshift.yaml
- 05-keycloak-user-adetalhouet.yaml
- 06-oauth.yaml

configMapGenerator:
- name: ca-config-map
  namespace: openshift-config
  files:
  - ca.crt

generatorOptions:
  disableNameSuffixHash: true