kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patches:
-  target:
     kind: ConsoleLink
     name: acs
   patch: |-
    - op: replace
      path: /spec/href
      value: 'https://central-stackrox.apps.hub-adetalhouet.rhtelco.io/main/dashboard'
-  target:
     kind: Job
     name: create-sso-auth-provider
     namespace: stackrox
   patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: >-
        https://keycloak-openshift-sso.apps.hub-adetalhouet.rhtelco.io/auth/realms/openshift
-  target:
     kind: Job
     name: create-sso-auth-provider
     namespace: stackrox
   patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: >-
        central-stackrox.apps.hub-adetalhouet.rhtelco.io