apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: mgnt-adetalhouet-nntsm-infra-ca-central-1a
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: mgnt-adetalhouet-nntsm
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: mgnt-adetalhouet-nntsm
      machine.openshift.io/cluster-api-machineset: mgnt-adetalhouet-nntsm-infra-ca-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: mgnt-adetalhouet-nntsm
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: mgnt-adetalhouet-nntsm-infra-ca-central-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: ca-central-1a
            region: ca-central-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5.2xlarge
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - mgnt-adetalhouet-nntsm-infra-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/mgnt-adetalhouet-nntsm
              value: owned
          deviceIndex: 0
          ami:
            id: ami-0baeff23c4cc6ddf5
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - mgnt-adetalhouet-nntsm-private-ca-central-1a
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: mgnt-adetalhouet-nntsm-worker-profile