apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: letsencrypt-ingresscontroller-clusterrole
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - ingresscontrollers
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: letsencrypt-certs-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: letsencrypt-ingresscontroller-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: letsencrypt-ingresscontroller-clusterrole
subjects:
  - kind: ServiceAccount
    name: letsencrypt-job-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: letsencrypt-certs-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: letsencrypt-certs-clusterrole
subjects:
  - kind: ServiceAccount
    name: letsencrypt-job-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: letsencrypt-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: letsencrypt-job-sa
