apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/01-openshift-gitops
    repoURL: https://github.com/adetalhouet/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true