apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performanceprofile
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  additionalKernelArgs:
    - nmi_watchdog=0
    - audit=0
    - mce=off
    - processor.max_cstate=1
    - idle=poll
    - intel_idle.max_cstate=0
#    - nosmt # disable hyperthreading
  cpu:
    isolated: 3-4
    reserved: 0-1
  globallyDisableIrqLoadBalancing: false
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 2
        node: 0
        size: 1G
  nodeSelector:
    node-role.kubernetes.io/worker-pao: ''
  realTimeKernel:
    enabled: true