---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cli-job-sa-role
rules:
  - apiGroups:
    - "*"
    resources: ["nodes"]
    verbs:
    - list
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cli-job-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: cli-job-sa
    namespace: openshift-gitops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cli-job-sa
  namespace: openshift-gitops