apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-sso

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: keycloak-migration
  files:
  - changelog.yaml
  - 01-realms.yaml
  - 02-clients.yaml
  - 03-users.yaml