apiVersion: v1
data:
  01-realms.yaml: |
    aWQ6IGFkZC1yZWFsbXMKYXV0aG9yOiBhZGV0YWxob3VldApjaGFuZ2VzOgogIC0gYWRkUm
    VhbG06CiAgICAgIG5hbWU6IG9wZW5zaGlmdA==
  02-clients.yaml: |
    aWQ6IGFkZC1vcGVuc2hpZnQtY2xpZW50CmF1dGhvcjogYWRldGFsaG91ZXQKcmVhbG06IG
    9wZW5zaGlmdApjaGFuZ2VzOgojIE9wZW5TaGlmdCBjbGllbnQKLSBhZGRTaW1wbGVDbGll
    bnQ6CiAgICBjbGllbnRJZDogb3BlbnNoaWZ0LXRlc3QKICAgIHNlY3JldDogbGludXg5IS
    FoZWNsLjQ4MDQuQUQKICAgIHJlZGlyZWN0VXJpczoKICAgICAgLSAiaHR0cHM6Ly9vYXV0
    aC1vcGVuc2hpZnQuYXBwcy5hcHBzLXVzZWFzdDItYWRldGFsaG91ZXQuYWRldGFsaG91ZX
    Qucmh0ZWxjby5pby9vYXV0aDJjYWxsYmFjay9rZXljbG9hayIKLSB1cGRhdGVDbGllbnQ6
    CiAgICBjbGllbnRJZDogb3BlbnNoaWZ0LXRlc3QKICAgIHN0YW5kYXJkRmxvd0VuYWJsZW
    Q6IHRydWUKICAgIGltcGxpY2l0Rmxvd0VuYWJsZWQ6IGZhbHNlCiAgICBkaXJlY3RBY2Nl
    c3NHcmFudEVuYWJsZWQ6IHRydWUKIyBBcmdvY2QgY2xpZW50Ci0gYWRkU2ltcGxlQ2xpZW
    50OgogICAgY2xpZW50SWQ6IGFyZ29jZC10ZXN0CiAgICBzZWNyZXQ6IGxpbnV4OSEhaGVj
    bC40ODA0LkFECiAgICByZWRpcmVjdFVyaXM6CiAgICAgIC0gImh0dHBzOi8vb3BlbnNoaW
    Z0LWdpdG9wcy1zZXJ2ZXItb3BlbnNoaWZ0LWdpdG9wcy5hcHBzLmFwcHMtdXNlYXN0Mi1h
    ZGV0YWxob3VldC5hZGV0YWxob3VldC5yaHRlbGNvLmlvL2F1dGgvY2FsbGJhY2siCi0gdX
    BkYXRlQ2xpZW50OgogICAgY2xpZW50SWQ6IGFyZ29jZC10ZXN0CiAgICBzdGFuZGFyZEZs
    b3dFbmFibGVkOiB0cnVlCiAgICBpbXBsaWNpdEZsb3dFbmFibGVkOiBmYWxzZQogICAgZG
    lyZWN0QWNjZXNzR3JhbnRFbmFibGVkOiB0cnVlCiAgICBiYXNlVXJsOiAvYXBwbGljYXRp
    b25zCiAgICByb290VXJsOiBodHRwczovL29wZW5zaGlmdC1naXRvcHMtc2VydmVyLW9wZW
    5zaGlmdC1naXRvcHMuYXBwcy5hcHBzLXVzZWFzdDItYWRldGFsaG91ZXQuYWRldGFsaG91
    ZXQucmh0ZWxjby5pbw==
  03-users.yaml: |
    aWQ6IGFkZC11c2VycwphdXRob3I6IGFkZXRhbGhvdWV0CmNoYW5nZXM6Ci0gYWRkVXNlcj
    oKICAgIHJlYWxtOiBvcGVuc2hpZnQKICAgIG5hbWU6IGFkZXRhbGhvdWV0CiAgICBlbmFi
    bGVkOiB0cnVlCiAgICBmaXJzdE5hbWU6IEFsZXhpcwogICAgbGFzdE5hbWU6IGRlIFRhbG
    hvdcOrdAogICAgYXR0cmlidXRlczoKICAgICAgZ3JvdXBzOgogICAgICAgIC0gQXJnb0NE
    QWRtaW5zCiAgLSB1cGRhdGVVc2VyUGFzc3dvcmQ6CiAgICAgIG5hbWU6IGFkZXRhbGhvdW
    V0CiAgICAgIHBhc3N3b3JkOiBsaW51eDkhIQ==
  changelog.yaml: |
    aW5jbHVkZXM6CiAgLSBwYXRoOiAwMS1yZWFsbS55bWwKICAtIHBhdGg6IDAyLWNsaWVudH
    MueW1sCiAgLSBwYXRoOiAwMy11c2Vycy55bWw=
kind: Secret
metadata:
  name: keycloak-migration
  namespace: openshift-sso
type: Opaque
